export const ScreenNames = {
  HomeScreen: 'HomeScreen',
  HomeTab:'Home',
  MyOrdersScreen: 'MyOrdersScreen',
//   ShoppingCartScreen: 'ShoppingCartScreen',
  WishlistScreen: 'WishlistScreen',
  ProfileScreen: 'ProfileScreen',
  OnboardingScreen2: 'OnboardingScreen2',
  SigninScreen: 'SigninScreen',
  SignupScreen: 'SignupScreen',
  AuthScreen: 'AuthScreen',
  CategoryScreen: 'CategoryScreen',
  ProductScreen: 'ProductScreen',
  DetailScreen: 'DetailScreen',
  SearchScreen: 'SearchScreen',
  FilterScreen: 'FilterScreen',
  ShoppingCartScreen: 'ShoppingCartScreen',
  ShoppingAddressScreen: 'ShoppingAddressScreen',
  AddNewCardScreen: 'AddNewCardScreen',
};